Private-events project
jrai0792/private-events pull request #1
Opened 2020-12-04 11:06 UTC by jrai0792

In this project, practiced associations between the models.
Implemented RSpec, Capibara, Factory-bot gems for writing unit test cases.

2020-12-04 12:19 UTC, trekab requested changes
### Changes Required! :recycle: 
Hi @jrai0792! So far so good! You have the associations right! :+1: To complete this project, I have added some feedback for you to work on (check the comments in the code too):
- [ ] You could improve your navigation by adding links to the events' index page and the user's show page. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/navigation_links_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- [ ] The user's show page should display events the user has created and events that the user is attending to separated into past and upcoming events. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- [ ]  Move your `spec` files to the spec folder. For model tests, just put them in the `spec/model` folder. Also, write some integration tests for your project. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2020-12-04 12:19 UTC, trekab commented on app/views/users/show.html.erb
> +      <li>
Move this logic to the user's controller in the `show` action, i.e. `@created_events = current_user.created_events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)). It is a better place for such logic than the view.

2020-12-04 12:19 UTC, trekab commented on app/controllers/application_controller.rb
> +    User.where(id: session[:user_id]).first
__[Optional]__ You don't have to use the `first` method here since the user id's are unique.

2020-12-04 12:19 UTC, trekab commented on app/views/users/show.html.erb
> +   <%@user.attended_events.each do |event| %>
This logic should be in the controller, e.g. `@past_events = current_user.attended_events.previous` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)). Then you can use `@past_events.each` in your view.

2020-12-06 15:00 UTC, BrittanyBlake commented on app/views/users/show.html.erb
> +      <% @user.created_events.each do |event|%>
- [ ] This logic should be in the show action of the users controller. This was pointed out to you in the previous review.
requirements 👇 

<img width="546" alt="Screen Shot 2020-12-06 at 9 58 45 AM" src="https://user-images.githubusercontent.com/48804258/101283625-a3151280-37a9-11eb-8700-6fd13006c7ee.png">

2020-12-06 15:38 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi @jrai0792 ! 👋 
You have also done a wonderful job with your project so far! It looks really good! 👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

- [ ] Your rspec isn't configured correctly. I can see that you have made tests but when i try to run it i get the following output. 👇 
<img width="500" alt="Screen Shot 2020-12-06 at 10 37 16 AM" src="https://user-images.githubusercontent.com/48804258/101284630-03f31980-37af-11eb-94b6-e5ff3fff818c.png">

- Please see my comments for a few other changes that need to be made.

****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2020-12-06 15:38 UTC, BrittanyBlake commented on app/views/users/show.html.erb
> +   <%@user.attended_events.each do |event| %>
- [ ] As was pointed out before, the logic for future events should be in your user controller. 
Screenshot from Odin project 👇 
<img width="834" alt="Screen Shot 2020-12-06 at 10 18 58 AM" src="https://user-images.githubusercontent.com/48804258/101284129-757d9880-37ac-11eb-9580-c2d27f98641e.png">

- **Note where it says you could put it in your views but you should not do that 👇** 
<img width="782" alt="Screen Shot 2020-12-06 at 10 20 08 AM" src="https://user-images.githubusercontent.com/48804258/101284228-ef158680-37ac-11eb-928b-bb07198853ba.png">

2020-12-06 15:38 UTC, BrittanyBlake commented on app/views/users/show.html.erb
> +      <% @user.created_events.each do |event|%>
- [ ] This logic should be in the show action of the users controller. This was pointed out to you in the previous review.
screenshot of requirements 👇 

<img width="546" alt="Screen Shot 2020-12-06 at 9 58 45 AM" src="https://user-images.githubusercontent.com/48804258/101283625-a3151280-37a9-11eb-8700-6fd13006c7ee.png">

2020-12-06 15:38 UTC, BrittanyBlake commented on app/views/users/show.html.erb
> +   <%@user.attended_events.each do |event| %>
- [ ] Like above, this should also be in the users controller. 
Screenshot from requirements 👇 
<img width="826" alt="Screen Shot 2020-12-06 at 10 27 31 AM" src="https://user-images.githubusercontent.com/48804258/101284393-c772ee00-37ad-11eb-99c5-1d4db1d2dfe2.png">

2020-12-06 18:13 UTC, kobiyoyo approved these changes
# Project Approved :thumbsup:
## Hello Team  ,  you have done a brilliant job with this project. :clap:
#### You can merge !!!

2020-12-07 03:22 UTC, merged